title:              My Data Science Journey
email:              catherinewang131@gmail.com
description:        Data tutorials, projects, stories
author:             Qingwen
baseurl:            ""
url:                "https://qwenw57.github.io"

# Social Profiles
twitter_username:   
github_username:    qwenw57
facebook_username:  
instagram_username:  
linkedin_username:  qingwen57

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge